'use client'
/* eslint-disable @next/next/no-img-element -- object URLs for file previews cannot be optimized by next/image. */
import { useRef, useState } from 'react'
import type { Log, Tracker } from '../../types'
import { api } from '../../lib/api'
const today = () => new Date().toISOString().slice(0, 10)
export function LogForm({ tracker, ownerToken, existing, onCreated }: { tracker: Tracker; ownerToken: string; existing: Log[]; onCreated: (log: Log) => void }) {
  const fileInput = useRef<HTMLInputElement>(null); const [content, setContent] = useState(''); const [topic, setTopic] = useState(tracker.topics[0]); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const choose = (next?: File) => { if (!next) return; if (!next.type.match(/^image\/(jpeg|png|gif|webp)$/) || next.size > 5 * 1024 * 1024) { setError('Choose a JPG, PNG, GIF, or WebP image under 5MB.'); return } setFile(next); setPreview(URL.createObjectURL(next)); setError('') }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (content.trim().length < 20 || !file) { setError('Write at least 20 characters and add an image.'); return } if (existing.some((log) => log.logged_date === today()) && !confirm('You already logged today. Add another entry?')) return; setSaving(true); setError(''); try { const data = new FormData(); data.set('content', content.trim()); data.set('topic_tag', topic); data.set('logged_date', today()); data.set('image', file); const log = await api.createLog(tracker.slug, ownerToken, data); onCreated(log); setContent(''); setFile(null); setPreview(''); if (fileInput.current) fileInput.current.value = '' } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save your log.') } finally { setSaving(false) } }
  return <form onSubmit={submit} className="glass rounded-2xl p-5 sm:p-6"><h2 className="font-display text-xl font-bold">Log today’s learning</h2><div className="mt-5 grid gap-4 sm:grid-cols-[160px_1fr]"><label className="text-sm font-semibold">Topic tag<select value={topic} onChange={(event) => setTopic(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-bg px-3 py-3 font-normal outline-none focus:border-mint">{tracker.topics.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-semibold">What did you learn?<textarea value={content} onChange={(event) => setContent(event.target.value)} maxLength={1000} rows={4} placeholder="What did you learn today? Be specific — future you will thank you." className="mt-2 w-full resize-y rounded-xl border border-white/10 bg-bg px-3 py-3 font-normal leading-6 outline-none focus:border-mint" /></label></div><p className="mt-1 text-right text-xs text-muted">{content.length}/1000</p><div onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); choose(event.dataTransfer.files[0]) }} onClick={() => fileInput.current?.click()} className="mt-4 cursor-pointer rounded-xl border border-dashed border-white/20 bg-white/[.025] p-5 text-center transition hover:border-mint"><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/gif,image/webp" className="hidden" onChange={(event) => choose(event.target.files?.[0])} />{preview ? <><img src={preview} alt="Selected log image preview" className="mx-auto h-48 max-w-full rounded-lg object-cover" /><button type="button" onClick={(event) => { event.stopPropagation(); setFile(null); setPreview(''); if (fileInput.current) fileInput.current.value = '' }} className="mt-3 text-xs font-bold text-red-300">Remove image</button></> : <><p className="font-semibold">Drop a screenshot, notes, or anything visual</p><p className="mt-1 text-xs text-muted">JPG, PNG, GIF, or WebP · 5MB max</p></>}</div>{error && <p className="mt-4 rounded-lg bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={saving} className="mt-5 rounded-xl bg-accent px-5 py-3 font-display font-bold disabled:opacity-50">{saving ? 'Adding log…' : 'Add Log →'}</button></form>
}
