'use client'
import { useMemo, useState } from 'react'
import type { Log } from '../../types'
import { Modal } from '../ui/Modal'
import { LogCard } from './LogCard'

const iso = (value: Date) => { const d = new Date(value); d.setHours(0, 0, 0, 0); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
const label = (date: string) => new Date(`${date}T00:00:00`).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })
export function StreakCalendar({ logs, isOwner, topics, onDelete }: { logs: Log[]; isOwner: boolean; topics: string[]; onDelete: (id: string) => Promise<void> }) {
  const [selected, setSelected] = useState<string | null>(null); const today = iso(new Date()); const days = useMemo(() => { const end = new Date(); end.setHours(0, 0, 0, 0); const mondayOffset = (end.getDay() + 6) % 7; end.setDate(end.getDate() - mondayOffset); return Array.from({ length: 84 }, (_, index) => { const day = new Date(end); day.setDate(end.getDate() - 83 + index); return day }) }, []); const logMap = new Map<string, Log[]>(); logs.forEach((log) => logMap.set(log.logged_date, [...(logMap.get(log.logged_date) ?? []), log])); const dayLogs = selected ? logMap.get(selected) ?? [] : []
  return <><section className="glass overflow-x-auto rounded-2xl p-5"><div className="mb-3 flex justify-between text-xs text-muted"><span>Last 12 weeks</span><span>● logged</span></div><div className="grid min-w-[560px] grid-cols-7 gap-2">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day) => <span key={day} className="text-center text-[10px] font-bold uppercase tracking-wide text-muted">{day}</span>)}{days.map((day) => { const date = iso(day); const active = logMap.has(date); return <button key={date} onClick={() => setSelected(date)} title={label(date)} className="group relative flex aspect-square items-center justify-center"><i className={`h-7 w-7 rounded-full transition group-hover:scale-110 ${active ? 'bg-accent shadow-[0_0_18px_rgba(108,99,255,.65)]' : 'bg-[#1E1E2E]'} ${date === today ? 'ring-2 ring-mint ring-offset-2 ring-offset-[#13131A]' : ''}`} />{day.getDate() === 1 && <small className="absolute -top-3 left-0 text-[9px] text-muted">{day.toLocaleDateString(undefined, { month: 'short' })}</small>}</button> })}</div></section>{selected && <Modal title={`Logs from ${label(selected)}`} onClose={() => setSelected(null)}>{dayLogs.length ? <div className="space-y-4">{dayLogs.map((log) => <LogCard key={log.id} log={log} topicIndex={Math.max(0, topics.indexOf(log.topic_tag))} isOwner={isOwner} onDelete={onDelete} />)}</div> : <p className="text-slate-400">No logs on this day.</p>}</Modal>}</>
}
